/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logica;

import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author MI EQUIPO
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    private Juego() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Juego Online Rescata Al Astronauta (Servidor)");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());

        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/imagenes/space.png"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Resumen = new javax.swing.JTextArea();
        asteroide1 = new javax.swing.JLabel();
        asteroide2 = new javax.swing.JLabel();
        ovni = new javax.swing.JLabel();
        gold = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TXTenviar = new javax.swing.JTextField();
        Send = new javax.swing.JButton();
        StartServer = new javax.swing.JButton();
        Nickname = new javax.swing.JTextField();
        Start = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        Restart = new javax.swing.JButton();
        estado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Resumen.setColumns(20);
        Resumen.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        Resumen.setRows(5);
        jScrollPane1.setViewportView(Resumen);

        asteroide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asteroid.png"))); // NOI18N

        asteroide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asteroide2.png"))); // NOI18N

        ovni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ovni.gif"))); // NOI18N

        gold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/astronauta.gif"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STATUS: ");

        Send.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        Send.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SendKeyPressed(evt);
            }
        });

        StartServer.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        StartServer.setText("Start Server");
        StartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartServerActionPerformed(evt);
            }
        });

        Nickname.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        Nickname.setText("Nickname");

        Start.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        Start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StartKeyPressed(evt);
            }
        });

        Pause.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });

        Restart.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });
        Restart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RestartKeyPressed(evt);
            }
        });

        estado.setFont(new java.awt.Font("Nirmala UI", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ovni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(asteroide1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gold)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(asteroide2)))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(Pause)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Start)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Restart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTenviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(Send, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(StartServer)))))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Pause)
                        .addComponent(Restart)
                        .addComponent(Start)
                        .addComponent(jLabel1))
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(asteroide2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ovni))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(gold)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(asteroide1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(StartServer)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Send))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed

        ChatServidor.servidor.enviarMSG(this.Nickname.getText() + " dice: \n"
                + this.TXTenviar.getText());

        if (ovni.getBounds().intersects(asteroide1.getBounds())
                || ovni.getBounds().intersects(asteroide2.getBounds())) {
            ChatServidor.servidor.enviarMSG(" TU GANAS !!!!!!! \n");
        }
        if (ovni.getBounds().intersects(gold.getBounds())) {
            ChatServidor.servidor.enviarMSG(" TU PIERDES !!!!!!! \n");
        }

        this.Resumen.setText(this.Resumen.getText() + "\n"
                + this.Nickname.getText() + " dice: \n"
                + this.TXTenviar.getText());

    }//GEN-LAST:event_SendActionPerformed

    private void StartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartServerActionPerformed
        ChatServidor.initServer();
        
    }//GEN-LAST:event_StartServerActionPerformed

    private void SendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SendKeyPressed
        int x = ovni.getX();
        int y = ovni.getY();

        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            y = y - 30;
            ovni.setLocation(x, y);
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            y = y + 30;
            ovni.setLocation(x, y);
        }

    }//GEN-LAST:event_SendKeyPressed

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        f1.suspend();
    }//GEN-LAST:event_PauseActionPerformed

    private void StartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StartKeyPressed
        int x = ovni.getX();
        int y = ovni.getY();

        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            y = y - 30;
            ovni.setLocation(x, y);
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            y = y + 30;
            ovni.setLocation(x, y);
        }
    }//GEN-LAST:event_StartKeyPressed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:
        f1.cargarDatos(this, asteroide1, asteroide2, ovni, gold, estado);
        f1.start();
        
    }//GEN-LAST:event_StartActionPerformed

    private void RestartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RestartKeyPressed
        int x = ovni.getX();
        int y = ovni.getY();

        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            y = y - 30;
            ovni.setLocation(x, y);
        }

        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            y = y + 30;
            ovni.setLocation(x, y);
        }
    }//GEN-LAST:event_RestartKeyPressed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        f1.resume();
    }//GEN-LAST:event_RestartActionPerformed

    Movimiento f1 = new Movimiento("A");

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Juego().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Nickname;
    private javax.swing.JButton Pause;
    private javax.swing.JButton Restart;
    public static javax.swing.JTextArea Resumen;
    private javax.swing.JButton Send;
    private javax.swing.JButton Start;
    private javax.swing.JButton StartServer;
    private javax.swing.JTextField TXTenviar;
    private javax.swing.JLabel asteroide1;
    private javax.swing.JLabel asteroide2;
    private javax.swing.JTextField estado;
    private javax.swing.JLabel gold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ovni;
    // End of variables declaration//GEN-END:variables

}
